```{r}
library(knitr)
```


# Getting started / FAQ for R

Author: Gene Leynes


Primary resources:
<li> http://rmarkdown.rstudio.com/
<li> http://stackoverflow.com/questions/tagged/R


Other great websites:
<li> http://www.statmethods.net/ Great place to learn general R concepts
<li> http://rprogramming.net/how-tos/
<li> http://manuals.bioinformatics.ucr.edu/home/programming-in-r
<li> http://pirategrunt.com/
<li> http://www.r-bloggers.com/
<li> http://en.wikibooks.org/wiki/R_Programming/Bayesian_Methods



```{r}
##------------------------------------------------------------------------------
## INITIALIZE
##------------------------------------------------------------------------------

## Remove all objects; perform garbage collection
rm(list=ls())
gc(reset=TRUE)

## Check for dependencies
if(!"geneorama" %in% rownames(installed.packages())){
    if(!"devtools" %in% rownames(installed.packages())){
        install.packages('devtools')
    }
    devtools::install_github('geneorama/geneorama')
}

## Load libraries
geneorama::detach_nonstandard_packages()
# geneorama::loadinstall_libraries(c("geneorama", "knitr", "caret", "gbm", 
# 								   "glmnet", "ROCR", "pROC", "plyr", "class", 
# 								   "hmeasure", "randomForest", 
# 								   "AppliedPredictiveModeling", "data.table", 
# 								   "doParallel", "e1071", "rpart"))
geneorama::loadinstall_libraries(c("geneorama", "knitr", "data.table"))

```


#### Example code to transfer libraries from a new R installation
```{r, eval=FALSE}
## First, install the new version of R

## After the new version of R is installed
## make v0 the path to your *old* library
## make v1 the path to the *new* library
v0 = 'C:/Users/375492/Documents/R/R-3.1.0/library/'
v1 = 'C:/Program Files/R/R-3.1.1/library'

## These are the packages that didn't copy over:
list.files(v0)[!list.files(v0)%in%list.files(v1)]

## Now, just install geneorama and then the missing 
## packages!
install.packages('devtools')
devtools::install_github("geneorama/geneorama")
library(geneorama)
loadinstall_libraries(list.files(v0)[!list.files(v0) %in% list.files(v1)])

```


### Load data from Yahoo
```{r}
library(geneorama)
loadinstall_libraries(c("fImport","data.table"))

# dat <- yahooImport("AAPL", frequency = "daily", 
# 				   from = "2014-01-01", to = "2014-09-22")
# dat@data@.Data[,"Adj.Close"]
# as.IDate(as.POSIXct(dat@data@positions, origin = "1970-01-01"))

YahooDownloader <- function(symbols, start, end, period = "daily"){
	# symbols <- c("IBM", "AAPL", "BAC")
	dat_list <- lapply(symbols, yahooImport, frequency = period, 
					   from = start, to = end)
	extraction_function <- function(LIST_DATA, DataColumn){
		dat_dt_list <- lapply(
			X = LIST_DATA, 
			FUN = function(x){
				dt <- data.table(
					date = as.IDate(as.POSIXct(x@data@positions, 
											   origin = "1970-01-01")),
					V1 = x@data@.Data[,DataColumn])
				setnames(dt, c("date", DataColumn))
				setkey(dt, date)
				dt
				}
			)
		dat <- Reduce(function(u,v)u[v], dat_dt_list)
		setnames(dat, c("date", symbols))
		return(dat)
	}
	## Loop over possible column names
	## colnames(dat_list[[1]]@data@.Data)
	YAHOO_DATA_NAMES <- c("Open", "High", "Low", "Close","Volume","Adj.Close")
	dat <- lapply(YAHOO_DATA_NAMES, extraction_function, LIST_DATA=dat_list)
	names(dat) <- YAHOO_DATA_NAMES
	return(dat)
}

dat <- YahooDownloader(symbols <- c("IBM", "AAPL", "BAC"),
					   start = "2014-01-01", end = "2014-09-21", period="daily")
dat_monthly <- YahooDownloader(symbols <- c("IBM", "AAPL", "BAC"),
					   start = "2014-01-01", end = "2014-09-21", period="monthly")

dat
dat_monthly

plot(AAPL~date, dat, type='o')

loadinstall_libraries("zoo")
plot(zoo(dat[,-1,with=F], order.by = dat$date))

```










